#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "No folder path provided, using current directory: $(pwd)"
    FOLDER_PATH=$(pwd)
else
    FOLDER_PATH=$1
fi

echo "Logging in to AWS public ECR..."
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
docker run -it --rm -v "$FOLDER_PATH":/app -w /app public.ecr.aws/kplatform/polycode/next-watcher:latest